### PR TITLE
Fix docs for R2

### PR DESCRIPTION
**Pull request by nicosuave**
```
ERROR: Invalid extra parameters: ENDPOINT (SQLSTATE P0001)
HINT: Allowed parameters are USE_SSL, REGION, END_POINT, SCOPE.
```

### CODE REVIEW

**Comment by nicosuave** [comment]
Y'all might also have a mismatch here with whatever underlying function gets called. 

Changing to `END_POINT` lets me properly create the secret from the SQL interface, but I'm still seeing 403s (looks like it's still hitting AWS).

**Comment by nicosuave** [comment]
Hmm looks like `ENDPOINT` is correct actually; weird https://github.com/Mooncake-Labs/pg_mooncake/blob/main/sql/pg_mooncake--0.0.1.sql#L44

**Comment by nicosuave** [comment]
I experienced the above with Neon FWIW

**Comment by dpxcc** [comment]
Neon does weekly updates and the next one is scheduled for tomorrow
Sorry, we should have waited for the update on Neon to complete before landing the diff
Could you please try again later tomorrow?

**Comment by dpxcc** [comment]
Correct, `END_POINT` was an typo in the old Neon build which is already fixed in `main` branch

**Comment by nicosuave** [comment]
No problem, sure

**Comment by dpxcc** [comment]
I’m sorry, but the release tag for this week’s Neon update was cut a few days ago. As a result, the pg_mooncake update will take effect next Wednesday instead of today.

**Pull request closed without merging**
